### ISSUE TITLE
Master Device Tutorial Doc Location

### ISSUE THREAD

**Issue by mapc-lachlanh** [ekondayan/libiolink#4]
Hey, overall, I have really liked this library, it has been helpful to me as I start learning C++ and my IFM AL1420. I have used the Device Driver tutorial to help build out my Baumer proximity sensor, but was hoping to build out a specific driver for my Master. The tutorials section seems to be missing this file for the master, but has the device driver tutorial. Is there a plan to re-add that or is that something I might find directly as a IFM resource elsewhere?

**Comment by ekondayan** [comment]
Hi,
it has been a while since last time I had played with IO-Link. Right now I do not have the spare time to write a tutorial for a master driver.

In general you should be able to copy the AL1352 driver and tailor it for AL1420. I remember that there were some differences between the datasheet and querying the device parameters from the device itself.

Regards,

**Comment by mapc-lachlanh** [comment]
Fair enough, thanks for getting back to me. It's good to hear that it would be easy enough to redesign it given specifics in the operators manual of the individual master. I decided to switch to a AL135X series master, so that should make it even easier to readjust from the header files you have. Appreciate the followup after all the time! (The AL1420 doesn't have the same IoT capability I realised, so I switched to make use of it. Fortunately, we are only trying to read sensor data via C++, so my use case hopefully won't be as complicated as needing fully operational drivers.)
